# https://community.home-assistant.io/t/moon-platform-with-moon-phases-pictures/86646/10
# nécessite les icones présents dans https://github.com/papo-o/home-assistant-config/tree/master/www/moon_phases
sensor:
  - platform: moon
  - platform: template
    sensors:
      moon_phases:
        entity_id: sensor.moon
        friendly_name: 'Lune'
        # value_template: '{{ states.sensor.moon.state }}'
        value_template: |-
          {% set phases = { 
          'new_moon':'Nouvelle lune',
          'waxing_crescent':'Premier croissant',
          'first_quarter':'Premier quartier',
          'waxing_gibbous':'Gibbeuse croissante',
          'full_moon':'Pleine lune',
          'waning_gibbous':'Gibbeuse décroissante',
          'last_quarter':'Dernier quartier',
          'waning_crescent':'Dernier croissant'}%}
          {% set phase = states('sensor.moon') %}
          {{ phases[phase] if phase in phases.keys() else 'phase lunaire inconnue' }}
        entity_picture_template: /local/moon_phases/{{ states.sensor.moon.state }}.png

  - platform: template
    sensors:
      solar_angle:
        friendly_name: "Angle du soleil"
        unit_of_measurement: '°'
        value_template: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"