# # https://github.com/papo-o/home-assistant-config/blob/master/integrations/vacances_domogeek.yaml
# # https://pon.fr/home-assistant-vacances-scolaires-domogeek

##################################################################################
##################################################################################
##################################################################################
 #   _____ ______ _   _  _____  ____  _____   _____ 
 #  / ____|  ____| \ | |/ ____|/ __ \|  __ \ / ____|
 # | (___ | |__  |  \| | (___ | |  | | |__) | (___  
 #  \___ \|  __| | . ` |\___ \| |  | |  _  / \___ \ 
 #  ____) | |____| |\  |____) | |__| | | \ \ ____) |
 # |_____/|______|_| \_|_____/ \____/|_|  \_\_____/ 
sensor:
##################################################################################
  - platform: rest # https://www.home-assistant.io/integrations/rest
    scan_interval: '01:00:00'
    name: vacances_domogeek_aujourdhui
    resource_template: |-
      {% set zone = 'B' %} {# Zone must be 'A', 'B' or 'C' #}
      http://domogeek.entropialux.com/schoolholiday/{{ zone }}/now

  - platform: rest # https://www.home-assistant.io/integrations/rest
    scan_interval: '01:00:00'
    name: vacances_domogeek_demain
    resource_template: |-
      {% set zone = 'B' %} {# Zone must be 'A', 'B' or 'C' #}
      http://domogeek.entropialux.com/schoolholiday/{{ zone }}/tomorrow

##################################################################################
##################################################################################
##################################################################################
 #  ____ _____ _   _          _______     __   _____ ______ _   _  _____  ____  _____   _____ 
 # |  _ \_   _| \ | |   /\   |  __ \ \   / /  / ____|  ____| \ | |/ ____|/ __ \|  __ \ / ____|
 # | |_) || | |  \| |  /  \  | |__) \ \_/ /  | (___ | |__  |  \| | (___ | |  | | |__) | (___  
 # |  _ < | | | . ` | / /\ \ |  _  / \   /    \___ \|  __| | . ` |\___ \| |  | |  _  / \___ \ 
 # | |_) || |_| |\  |/ ____ \| | \ \  | |     ____) | |____| |\  |____) | |__| | | \ \ ____) |
 # |____/_____|_| \_/_/    \_\_|  \_\ |_|    |_____/|______|_| \_|_____/ \____/|_|  \_\_____/ 
binary_sensor:
#https://www.home-assistant.io/integrations/binary_sensor/
##################################################################################
  - platform: template #https://www.home-assistant.io/integrations/template/
    sensors:
      vacances_scolaires_domogeek_aujourdhui:
        friendly_name: "Vacances domogeek aujourd'hui"
        value_template: |-
          {% if is_state('sensor.vacances_domogeek_aujourdhui', 'False') %} 
          false
          {% else %} 
          true
          {% endif %}

  - platform: template # https://www.home-assistant.io/integrations/template/
    sensors:
      vacances_scolaires_domogeek_demain:
        friendly_name: "Vacances domogeek demain"
        value_template: |-
          {% if is_state('sensor.vacances_domogeek_demain', 'False') %} 
          false
          {% else %} 
          true
          {% endif %}
