# # https://www.home-assistant.io/integrations/rest
# # https://pon.fr/home-assistant-vacances-scolaires/
# # https://github.com/papo-o/home-assistant-config/blob/master/integrations/vacances_scolaires.yaml
# # vous avez deux choses à personnaliser, la zone et l'académie
# #   {% set zone = 'A' %}
# #   {% set location = 'Limoges' %}

homeassistant:
  customize:

    sensor.vacances_scolaires:
      friendly_name: "Vacances"
      icon: mdi:check-circle

sensor:
  - platform: rest
    scan_interval: '00:30:00'
    name: vacances_scolaires
    json_attributes_path: "$.records[0].fields"
    json_attributes:
      - start_date
      - end_date
      - description
    resource_template: |-
      {% set rows = '1'%}
      {% set zone = 'A' %}
      {% set location = 'Limoges' %}
      {% set dayOfYear =  now().strftime('%j') %}
      {% set year =  now().strftime('%Y') | int %}
      {% set lastYear = year - 1 %}
      {% set nextYear = year + 1 %}
      {% if dayOfYear > '182' %}
      {% set schoolYear = (year | string) + "-" + (nextYear | string) %}
      {%- else -%}
      {% set schoolYear = (lastYear | string) + "-" + (year | string) %}
      {%- endif %}
      https://data.education.gouv.fr/api/records/1.0/search/?dataset=fr-en-calendrier-scolaire&facet=start_date&facet=end_date&refine.zones=Zone+{{zone}}&rows=1&refine.annee_scolaire={{schoolYear}}&refine.location={{location}}
    value_template: |-
      {% set aujourdhui = now().strftime('%Y-%m-%d')%}
      {% for record in value_json.records -%}
      {% if aujourdhui >= record.fields.start_date and aujourdhui <= record.fields.end_date %} 
      {%- if record.fields.description %}{{record.fields.description}} jusqu'au {{record.fields.end_date}}{% endif %}
      {% else %} 
      {%- if record.fields.description %} prochaines : {{record.fields.description}} {{record.fields.start_date}}{% endif %}
      {% endif %}
      {%- endfor %}

binary_sensor:
  - platform: template
    sensors:
      vacances_scolaires_aujourdhui:
        friendly_name: "Vacances Scolaires aujourd'hui"
        value_template: |-
          {% set aujourdhui = now().strftime('%Y-%m-%d')%}
          {% if aujourdhui < states.sensor.vacances_scolaires.attributes["start_date"] or aujourdhui > states.sensor.vacances_scolaires.attributes["end_date"] %}
          false
          {% else %} 
          true
          {% endif %}

  - platform: template
    sensors:
      vacances_scolaires_demain:
        friendly_name: "Vacances Scolaires demain"
        value_template: |-
          {% set demain = (as_timestamp(now()) + (24*3600)) | timestamp_custom('%Y-%m-%d', True) %}
          {% if demain < states.sensor.vacances_scolaires.attributes["start_date"] or demain > states.sensor.vacances_scolaires.attributes["end_date"] %} 
          false
          {% else %} 
          true
          {% endif %}
