# https://www.home-assistant.io/integrations/rest

homeassistant:
  customize:

    sensor.utilisateurs_wordpress:
      icon: mdi:wordpress

sensor:

- platform: rest
  resource: https://pon.fr/wp-json/wp/v2/pages/?slug=register
  name: Utilisateurs Wordpress
  value_template: '{{ ((value_json[0].content.rendered).split(">")[2].split("<")[0] | float) | round(0) }}'
  scan_interval: 3600



